stages:
  - deploy

deploy_dev:
  stage: deploy
  only:
    - dev

  before_script:
    # instala ssh e rsync
    - apt-get update -y
    - apt-get install -y openssh-client rsync

    # inicia ssh-agent
    - eval $(ssh-agent -s)

    # adiciona chave privada
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    # prepara ssh
    - mkdir -p ~/.ssh

    # adiciona o container server-dev como host confiável
    - ssh-keyscan server-dev >> ~/.ssh/known_hosts

  script:
    # copia arquivos para o container
    - rsync -av --exclude='.git' ./ deploy@server-dev:/tmp/deploy

    # executa deploy
    - ssh deploy@server-dev "
        cd /tmp/deploy &&
        make deploy
      "