  stages:
    - deploy

  #DEPLOY DEBUG
  debug_pipeline:
    stage: deploy
    script:
      - 'echo "Branch: $CI_COMMIT_BRANCH"'
      - 'echo "Tag: $CI_COMMIT_TAG"'

  # DEPLOY TEMPLATE
  .deploy_template:
    stage: deploy
    before_script:
      # Atualiza pacotes e instala dependências necessárias
      - apt-get update -y
      - apt-get install -y openssh-client rsync

      # Inicia o agente SSH
      - eval $(ssh-agent -s)

      # Adiciona a chave privada (vinda de variável de ambiente do GitLab)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

      # Cria diretório de configuração do SSH
      - mkdir -p ~/.ssh

      # Adiciona o host remoto como confiável (evita prompt interativo)
      - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
    script:
      - |
        if [ -n "$CI_COMMIT_TAG" ]; then
          VERSION="$CI_COMMIT_TAG"   # Se for tag (beta/prod)
        else
          VERSION="$CI_COMMIT_BRANCH" # Se for branch (dev/homolog)
        fi
        echo "Versão detectada: $VERSION"
        sed -i "s|{{VERSION}}|$VERSION|g" index.html
      - |
        DEPLOY_DATETIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo "Data de deploy: $DEPLOY_DATETIME"
        sed -i "s|{{DEPLOY_DATETIME}}|$DEPLOY_DATETIME|g" index.html
      - |
        DEPLOY_USER=$(git log -1 --pretty=format:'%an')
        echo "Usuário de deploy: $DEPLOY_USER"
        sed -i "s|{{DEPLOY_USER}}|$DEPLOY_USER|g" index.html

      # Sincroniza arquivos para o servidor remoto
      - rsync -av --exclude='.git' ./ deploy@$DEPLOY_HOST:/tmp/deploy

      # Executa comando de deploy no servidor remoto
      - ssh deploy@$DEPLOY_HOST "
          cd /tmp/deploy &&
          make deploy
        "

  # DEPLOY DEV
  deploy_dev:
    extends: .deploy_template
    only:
      - dev
    variables:
      DEPLOY_HOST: server-dev

  # DEPLOY HOMOLOG
  deploy_homolog:
    extends: .deploy_template
    rules:
      - if: '$CI_COMMIT_BRANCH =~ /^release\/v\d+\.\d+\.0$/'
    variables:
      DEPLOY_HOST: server-homolog

  # DEPLOY BETA
  deploy_beta:
    extends: .deploy_template
    rules:
      - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.0-beta\d+$/'
    variables:
      DEPLOY_HOST: server-beta

  # DEPLOY PROD
  deploy_prod:
    extends: .deploy_template
    rules:
      - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
    variables:
      DEPLOY_HOST: server-prod