server {
    listen 80;

    server_name localhost;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # 🔥 endpoint de teste
    location /test {
        return 200 '{"message":"deploy funcionando 🚀"}';
        add_header Content-Type application/json;
    }
}